version = 1
root = "93fd9bbd-acaa-4fc9-8200-bac50cf322a5"

[[samples]]
id = "93fd9bbd-acaa-4fc9-8200-bac50cf322a5"
name = "Acid Rack"
kind = "sound"

[[samples.graph.nodes]]
id = "b831bd38-ca08-40a5-a1e3-ff9775d2ce39"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 110.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "c1fb92c4-752a-4130-8a10-4e0382793c1f"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 110.0

[samples.graph.nodes.kind.props.detune]
value = 8.0

[[samples.graph.nodes]]
id = "ac085d07-5a40-4d42-a4d1-1c1ed2be92d1"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.5

[[samples.graph.nodes]]
id = "d8b72c4e-88ba-4931-9f4e-65f95b97a3bd"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "9776bad0-d2d8-4f7c-b279-dc597e19ad7b"

[[samples.graph.nodes.kind.props.inputs]]
port = "crush"
value = 4.0

[[samples.graph.nodes.kind.props.inputs]]
port = "ring"
value = 160.0

[[samples.graph.nodes]]
id = "79b27dc3-7afd-4019-884d-69315fb18776"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 3500.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 3500.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 350.0
time = 0.7

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 11.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "1a1fc5d6-d04d-4e19-a347-1e97e2827740"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.6000000238418579
time = 0.01

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 1.31

[[samples.graph.nodes]]
id = "37c9f46e-558a-4709-b4f9-7034f72036f1"

[samples.graph.nodes.kind]
kind = "delay"

[samples.graph.nodes.kind.props]
max_delay_time = 0.5

[samples.graph.nodes.kind.props.delay_time]
value = 0.1899999976158142

[[samples.graph.nodes]]
id = "2df41ae7-829f-4d8b-a27a-5588d2dfa518"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.30000001192092896

[[samples.graph.nodes]]
id = "60e0a237-cf12-4379-8c79-7020ae181e1b"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.8999999761581421

[[samples.graph.nodes]]
id = "c3d27583-7922-488d-aeb9-2f08819de5ef"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 5.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "ba86d031-be22-4803-a124-55462896898c"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 700.0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "b831bd38-ca08-40a5-a1e3-ff9775d2ce39"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "ac085d07-5a40-4d42-a4d1-1c1ed2be92d1"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "c1fb92c4-752a-4130-8a10-4e0382793c1f"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "ac085d07-5a40-4d42-a4d1-1c1ed2be92d1"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "ac085d07-5a40-4d42-a4d1-1c1ed2be92d1"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "d8b72c4e-88ba-4931-9f4e-65f95b97a3bd"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d8b72c4e-88ba-4931-9f4e-65f95b97a3bd"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "79b27dc3-7afd-4019-884d-69315fb18776"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "79b27dc3-7afd-4019-884d-69315fb18776"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "1a1fc5d6-d04d-4e19-a347-1e97e2827740"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "1a1fc5d6-d04d-4e19-a347-1e97e2827740"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "60e0a237-cf12-4379-8c79-7020ae181e1b"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "1a1fc5d6-d04d-4e19-a347-1e97e2827740"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "37c9f46e-558a-4709-b4f9-7034f72036f1"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "37c9f46e-558a-4709-b4f9-7034f72036f1"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "2df41ae7-829f-4d8b-a27a-5588d2dfa518"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "2df41ae7-829f-4d8b-a27a-5588d2dfa518"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "60e0a237-cf12-4379-8c79-7020ae181e1b"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "c3d27583-7922-488d-aeb9-2f08819de5ef"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "ba86d031-be22-4803-a124-55462896898c"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "ba86d031-be22-4803-a124-55462896898c"
output = 0

[samples.graph.connections.to]
to = "node_param"
node = "79b27dc3-7afd-4019-884d-69315fb18776"
param = "frequency"

[samples.trigger]
release = 0.0

[[samples]]
id = "9776bad0-d2d8-4f7c-b279-dc597e19ad7b"
name = "FX Rack"
kind = "sound"

[[samples.graph.nodes]]
id = "b8834f29-03a2-4c32-8e21-c98579034cc0"

[samples.graph.nodes.kind]
kind = "audio_worklet"

[samples.graph.nodes.kind.props]
module = "b6e8fe21-2920-4bbb-8bd8-bf2fa1135680"
processor_name = "bitcrusher"

[[samples.graph.nodes.kind.props.parameters]]
name = "bits"
min = 1.0
max = 16.0

[samples.graph.nodes.kind.props.parameters.param]
value = 8.0

[[samples.graph.nodes.kind.props.parameters]]
name = "reduction"
min = 1.0
max = 32.0

[samples.graph.nodes.kind.props.parameters.param]
value = 4.0

[[samples.graph.nodes]]
id = "8b81465b-9695-4b0f-9544-e108754ddf9f"

[samples.graph.nodes.kind]
kind = "audio_worklet"

[samples.graph.nodes.kind.props]
module = "c094ec42-b6e2-4018-ad5f-84b26def890b"
processor_name = "ringmod"

[[samples.graph.nodes.kind.props.parameters]]
name = "freq"
min = 20.0
max = 2000.0

[samples.graph.nodes.kind.props.parameters.param]
value = 220.0

[[samples.graph.nodes.kind.props.parameters]]
name = "mix"
min = 0.0
max = 1.0

[samples.graph.nodes.kind.props.parameters.param]
value = 0.6000000238418579

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "inlet"
port = "in"

[samples.graph.connections.to]
to = "node_input"
node = "b8834f29-03a2-4c32-8e21-c98579034cc0"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "b8834f29-03a2-4c32-8e21-c98579034cc0"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "8b81465b-9695-4b0f-9544-e108754ddf9f"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "8b81465b-9695-4b0f-9544-e108754ddf9f"
output = 0

[samples.graph.connections.to]
to = "outlet"
port = "out"

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "inlet"
port = "crush"

[samples.graph.connections.to]
to = "node_param"
node = "b8834f29-03a2-4c32-8e21-c98579034cc0"
param = "bits"

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "inlet"
port = "ring"

[samples.graph.connections.to]
to = "node_param"
node = "8b81465b-9695-4b0f-9544-e108754ddf9f"
param = "freq"

[[samples.graph.inlets]]
id = "in"

[[samples.graph.inlets]]
id = "crush"
default = 8.0

[[samples.graph.inlets]]
id = "ring"
default = 220.0

[[samples.graph.outlets]]
id = "out"

[samples.trigger]
release = 0.0

[[assets.wasm_modules]]
id = "b6e8fe21-2920-4bbb-8bd8-bf2fa1135680"
label = "bitcrusher"

[assets.wasm_modules.source]
kind = "path"
data = "assets/b6e8fe21-2920-4bbb-8bd8-bf2fa1135680.wasm"

[[assets.wasm_modules]]
id = "c094ec42-b6e2-4018-ad5f-84b26def890b"
label = "ringmod"

[assets.wasm_modules.source]
kind = "path"
data = "assets/c094ec42-b6e2-4018-ad5f-84b26def890b.wasm"
