version = 1
root = "092ea00f-3202-4d4b-9633-40dd7994aafa"

[[samples]]
id = "092ea00f-3202-4d4b-9633-40dd7994aafa"
name = "Chord Stab"
kind = "sound"

[[samples.graph.nodes]]
id = "bf5d5f15-96db-4198-898f-f929ad6ee477"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.5

[[samples.graph.nodes]]
id = "efd2c978-d1d4-4a3d-ac4d-4a1075acbff8"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "4d087c62-3d1c-486f-a349-de7ae756df98"

[[samples.graph.nodes.kind.props.inputs]]
port = "pitch"
value = 220.0

[[samples.graph.nodes.kind.props.inputs]]
port = "cutoff"
value = 1400.0

[[samples.graph.nodes]]
id = "ad2f8a47-4db8-407a-b927-f3d9d0218481"

[samples.graph.nodes.kind]
kind = "stereo_panner"

[samples.graph.nodes.kind.props.pan]
value = -0.6000000238418579

[[samples.graph.nodes]]
id = "37bd9aaa-5c1b-4038-b2ad-397136ecb12b"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "4d087c62-3d1c-486f-a349-de7ae756df98"

[[samples.graph.nodes.kind.props.inputs]]
port = "pitch"
value = 261.6300048828125

[[samples.graph.nodes.kind.props.inputs]]
port = "cutoff"
value = 1900.0

[[samples.graph.nodes]]
id = "695fd373-efe4-43f7-9d61-11013b608c2c"

[samples.graph.nodes.kind]
kind = "stereo_panner"

[samples.graph.nodes.kind.props.pan]
value = -0.20000000298023224

[[samples.graph.nodes]]
id = "5a1c5bd6-1c1f-4990-8897-aecb255b6460"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "4d087c62-3d1c-486f-a349-de7ae756df98"

[[samples.graph.nodes.kind.props.inputs]]
port = "pitch"
value = 329.6300048828125

[[samples.graph.nodes.kind.props.inputs]]
port = "cutoff"
value = 2600.0

[[samples.graph.nodes]]
id = "7f5c27d8-cefd-4e15-9b2d-464e1f122181"

[samples.graph.nodes.kind]
kind = "stereo_panner"

[samples.graph.nodes.kind.props.pan]
value = 0.25

[[samples.graph.nodes]]
id = "8933e34d-3e70-4184-9c3a-8e5e6a6644b9"

[samples.graph.nodes.kind]
kind = "sample"

[samples.graph.nodes.kind.props]
sample = "4d087c62-3d1c-486f-a349-de7ae756df98"

[[samples.graph.nodes.kind.props.inputs]]
port = "pitch"
value = 392.0

[[samples.graph.nodes.kind.props.inputs]]
port = "cutoff"
value = 3400.0

[[samples.graph.nodes]]
id = "52a68e25-a6bd-4e3c-a28e-db31d448dc14"

[samples.graph.nodes.kind]
kind = "stereo_panner"

[samples.graph.nodes.kind.props.pan]
value = 0.6000000238418579

[[samples.graph.nodes]]
id = "0cbe0ee1-4be2-4de2-a202-63ef84b6add2"

[samples.graph.nodes.kind]
kind = "audio_worklet"

[samples.graph.nodes.kind.props]
module = "a190e2e7-88de-4f37-813c-8e628380f7f1"
processor_name = "drive"

[[samples.graph.nodes.kind.props.parameters]]
name = "drive"
min = 1.0
max = 30.0

[samples.graph.nodes.kind.props.parameters.param]
value = 6.0

[[samples.graph.nodes.kind.props.parameters]]
name = "mix"
min = 0.0
max = 1.0

[samples.graph.nodes.kind.props.parameters.param]
value = 0.8500000238418579

[[samples.graph.nodes.kind.props.parameters]]
name = "level"
min = 0.0
max = 1.0

[samples.graph.nodes.kind.props.parameters.param]
value = 0.699999988079071

[[samples.graph.nodes]]
id = "5c6ed894-6c3d-4797-b8b6-ff1f599402e0"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.8999999761581421

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "efd2c978-d1d4-4a3d-ac4d-4a1075acbff8"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "ad2f8a47-4db8-407a-b927-f3d9d0218481"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "ad2f8a47-4db8-407a-b927-f3d9d0218481"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "bf5d5f15-96db-4198-898f-f929ad6ee477"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "37bd9aaa-5c1b-4038-b2ad-397136ecb12b"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "695fd373-efe4-43f7-9d61-11013b608c2c"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "695fd373-efe4-43f7-9d61-11013b608c2c"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "bf5d5f15-96db-4198-898f-f929ad6ee477"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "5a1c5bd6-1c1f-4990-8897-aecb255b6460"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "7f5c27d8-cefd-4e15-9b2d-464e1f122181"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "7f5c27d8-cefd-4e15-9b2d-464e1f122181"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "bf5d5f15-96db-4198-898f-f929ad6ee477"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "8933e34d-3e70-4184-9c3a-8e5e6a6644b9"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "52a68e25-a6bd-4e3c-a28e-db31d448dc14"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "52a68e25-a6bd-4e3c-a28e-db31d448dc14"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "bf5d5f15-96db-4198-898f-f929ad6ee477"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "bf5d5f15-96db-4198-898f-f929ad6ee477"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "0cbe0ee1-4be2-4de2-a202-63ef84b6add2"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "0cbe0ee1-4be2-4de2-a202-63ef84b6add2"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "5c6ed894-6c3d-4797-b8b6-ff1f599402e0"
input = 0

[samples.trigger]
release = 0.0

[[samples]]
id = "4d087c62-3d1c-486f-a349-de7ae756df98"
name = "Voice"
kind = "sound"

[[samples.graph.nodes]]
id = "1f10821b-bec4-449b-96f6-3eb058cf9cec"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 220.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "ce9c3b55-541d-4c98-8440-892db7d86aa2"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 2000.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 7.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "46526e2b-53a9-4c71-a62c-05e59bae0460"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.4000000059604645
time = 0.005

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 1.105

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "inlet"
port = "pitch"

[samples.graph.connections.to]
to = "node_param"
node = "1f10821b-bec4-449b-96f6-3eb058cf9cec"
param = "frequency"

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "inlet"
port = "cutoff"

[samples.graph.connections.to]
to = "node_param"
node = "ce9c3b55-541d-4c98-8440-892db7d86aa2"
param = "frequency"

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "1f10821b-bec4-449b-96f6-3eb058cf9cec"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "ce9c3b55-541d-4c98-8440-892db7d86aa2"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "ce9c3b55-541d-4c98-8440-892db7d86aa2"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "46526e2b-53a9-4c71-a62c-05e59bae0460"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "46526e2b-53a9-4c71-a62c-05e59bae0460"
output = 0

[samples.graph.connections.to]
to = "outlet"
port = "out"

[[samples.graph.inlets]]
id = "pitch"
default = 220.0

[[samples.graph.inlets]]
id = "cutoff"
default = 2000.0

[[samples.graph.outlets]]
id = "out"

[samples.trigger]
release = 0.0

[[assets.wasm_modules]]
id = "a190e2e7-88de-4f37-813c-8e628380f7f1"
label = "drive"

[assets.wasm_modules.source]
kind = "path"
data = "assets/a190e2e7-88de-4f37-813c-8e628380f7f1.wasm"
