version = 1
root = "cc9ca9e8-2c2d-4ad5-82d4-c2193c9fdd6e"

[[samples]]
id = "cc9ca9e8-2c2d-4ad5-82d4-c2193c9fdd6e"
name = "Crush"
kind = "sound"

[[samples.graph.nodes]]
id = "4f3a051a-b295-432a-8515-c56c8f4345f4"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 110.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "d54074ed-dc95-49d6-ae5f-c8b6053d4a0b"

[samples.graph.nodes.kind]
kind = "audio_worklet"

[samples.graph.nodes.kind.props]
module = "f2c08804-f607-4a47-a4a8-d824005e3e81"
processor_name = "bitcrusher"

[[samples.graph.nodes.kind.props.parameters]]
name = "bits"
min = 1.0
max = 16.0

[samples.graph.nodes.kind.props.parameters.param]
value = 5.0

[[samples.graph.nodes.kind.props.parameters]]
name = "reduction"
min = 1.0
max = 32.0

[samples.graph.nodes.kind.props.parameters.param]
value = 6.0

[[samples.graph.nodes]]
id = "878dcd7d-1e43-448b-ae3f-f626c4310661"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 3500.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 3500.0
time = 0.0

[[samples.graph.nodes.kind.props.frequency.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.frequency.automation.args]
value = 400.0
time = 0.5

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 6.0

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "05590960-e536-4f0a-a8c4-38aaa869d0bf"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.699999988079071
time = 0.005

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.605

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "4f3a051a-b295-432a-8515-c56c8f4345f4"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "d54074ed-dc95-49d6-ae5f-c8b6053d4a0b"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "d54074ed-dc95-49d6-ae5f-c8b6053d4a0b"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "878dcd7d-1e43-448b-ae3f-f626c4310661"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "878dcd7d-1e43-448b-ae3f-f626c4310661"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "05590960-e536-4f0a-a8c4-38aaa869d0bf"
input = 0

[samples.trigger]
release = 0.0

[[assets.wasm_modules]]
id = "f2c08804-f607-4a47-a4a8-d824005e3e81"
label = "bitcrusher"

[assets.wasm_modules.source]
kind = "path"
data = "assets/f2c08804-f607-4a47-a4a8-d824005e3e81.wasm"
