version = 1
root = "6a77db96-c319-4800-a39d-1681c95276a7"

[[samples]]
id = "6a77db96-c319-4800-a39d-1681c95276a7"
name = "Drive"
kind = "sound"

[[samples.graph.nodes]]
id = "e3de3203-03aa-469a-9f6c-cf0cbe487835"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 110.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "1b782738-a673-4f27-b8d8-080925a3ec72"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sawtooth"

[samples.graph.nodes.kind.props.frequency]
value = 110.0

[samples.graph.nodes.kind.props.detune]
value = 11.0

[[samples.graph.nodes]]
id = "acbd44af-d0c9-4420-badc-85da312c5cd9"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.5

[[samples.graph.nodes]]
id = "6d60d450-bbac-44fd-9490-5b4461ccef1d"

[samples.graph.nodes.kind]
kind = "audio_worklet"

[samples.graph.nodes.kind.props]
module = "9ebf2eb7-ba5c-4807-956d-311f3413b66b"
processor_name = "drive"

[[samples.graph.nodes.kind.props.parameters]]
name = "drive"
min = 1.0
max = 30.0

[samples.graph.nodes.kind.props.parameters.param]
value = 14.0

[[samples.graph.nodes.kind.props.parameters]]
name = "mix"
min = 0.0
max = 1.0

[samples.graph.nodes.kind.props.parameters.param]
value = 1.0

[[samples.graph.nodes.kind.props.parameters]]
name = "level"
min = 0.0
max = 1.0

[samples.graph.nodes.kind.props.parameters.param]
value = 0.6000000238418579

[[samples.graph.nodes]]
id = "b5e430c3-c21e-4017-ba26-28f2e600e8c1"

[samples.graph.nodes.kind]
kind = "biquad_filter"

[samples.graph.nodes.kind.props]
type = "lowpass"

[samples.graph.nodes.kind.props.frequency]
value = 2200.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[samples.graph.nodes.kind.props.Q]
value = 0.800000011920929

[samples.graph.nodes.kind.props.gain]
value = 0.0

[[samples.graph.nodes]]
id = "724faebd-fc79-47db-a5e0-95e28909e40d"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.699999988079071
time = 0.01

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 1.41

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "e3de3203-03aa-469a-9f6c-cf0cbe487835"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "acbd44af-d0c9-4420-badc-85da312c5cd9"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "1b782738-a673-4f27-b8d8-080925a3ec72"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "acbd44af-d0c9-4420-badc-85da312c5cd9"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "acbd44af-d0c9-4420-badc-85da312c5cd9"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "6d60d450-bbac-44fd-9490-5b4461ccef1d"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "6d60d450-bbac-44fd-9490-5b4461ccef1d"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "b5e430c3-c21e-4017-ba26-28f2e600e8c1"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "b5e430c3-c21e-4017-ba26-28f2e600e8c1"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "724faebd-fc79-47db-a5e0-95e28909e40d"
input = 0

[samples.trigger]
release = 0.0

[[assets.wasm_modules]]
id = "9ebf2eb7-ba5c-4807-956d-311f3413b66b"
label = "drive"

[assets.wasm_modules.source]
kind = "path"
data = "assets/9ebf2eb7-ba5c-4807-956d-311f3413b66b.wasm"
