version = 1
root = "2f5c9759-b238-4c83-b9af-2f695d35cd26"

[[samples]]
id = "2f5c9759-b238-4c83-b9af-2f695d35cd26"
name = "Ring Mod"
kind = "sound"

[[samples.graph.nodes]]
id = "72cf3bb7-3e87-40fd-93c1-6a3434456ebe"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 440.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "5570bb80-78e3-47fb-a807-fabb83f247d5"

[samples.graph.nodes.kind]
kind = "audio_worklet"

[samples.graph.nodes.kind.props]
module = "a8e137a2-a67d-4b4e-ab3c-df362b814ad9"
processor_name = "ringmod"

[[samples.graph.nodes.kind.props.parameters]]
name = "freq"
min = 20.0
max = 2000.0

[samples.graph.nodes.kind.props.parameters.param]
value = 220.0

[[samples.graph.nodes.kind.props.parameters]]
name = "mix"
min = 0.0
max = 1.0

[samples.graph.nodes.kind.props.parameters.param]
value = 1.0

[[samples.graph.nodes]]
id = "91cda02d-7f8d-4d66-a0d1-e450fdc73a89"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 0.00009999999747378752

[[samples.graph.nodes.kind.props.gain.automation]]
event = "set_value"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 0.0

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.6000000238418579
time = 0.005

[[samples.graph.nodes.kind.props.gain.automation]]
event = "exponential_ramp"

[samples.graph.nodes.kind.props.gain.automation.args]
value = 0.00009999999747378752
time = 1.605

[[samples.graph.nodes]]
id = "98a8ada3-6cdc-48fd-8c4f-7ffbaa5ae69b"

[samples.graph.nodes.kind]
kind = "oscillator"

[samples.graph.nodes.kind.props]
type = "sine"

[samples.graph.nodes.kind.props.frequency]
value = 6.0

[samples.graph.nodes.kind.props.detune]
value = 0.0

[[samples.graph.nodes]]
id = "89a1b8fb-852f-45f9-a219-786a701bbfb5"

[samples.graph.nodes.kind]
kind = "gain"

[samples.graph.nodes.kind.props.gain]
value = 120.0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "72cf3bb7-3e87-40fd-93c1-6a3434456ebe"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "5570bb80-78e3-47fb-a807-fabb83f247d5"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "5570bb80-78e3-47fb-a807-fabb83f247d5"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "91cda02d-7f8d-4d66-a0d1-e450fdc73a89"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "98a8ada3-6cdc-48fd-8c4f-7ffbaa5ae69b"
output = 0

[samples.graph.connections.to]
to = "node_input"
node = "89a1b8fb-852f-45f9-a219-786a701bbfb5"
input = 0

[[samples.graph.connections]]

[samples.graph.connections.from]
from = "node_output"
node = "89a1b8fb-852f-45f9-a219-786a701bbfb5"
output = 0

[samples.graph.connections.to]
to = "node_param"
node = "5570bb80-78e3-47fb-a807-fabb83f247d5"
param = "freq"

[samples.trigger]
release = 0.0

[[assets.wasm_modules]]
id = "a8e137a2-a67d-4b4e-ab3c-df362b814ad9"
label = "ringmod"

[assets.wasm_modules.source]
kind = "path"
data = "assets/a8e137a2-a67d-4b4e-ab3c-df362b814ad9.wasm"
